require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

target 'enatbet' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    # Fix for BoringSSL-GRPC, gRPC-Core, and gRPC-C++ (Xcode 16 compatibility)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Consistent deployment target
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        
        # Fix for problematic gRPC/Firebase dependencies
        if ['BoringSSL-GRPC', 'gRPC-Core', 'gRPC-C++'].include?(target.name)
          # CRITICAL: Disable treating warnings as errors
          config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          
          # Suppress the C++20 template warning
          config.build_settings['WARNING_CFLAGS'] ||= ['$(inherited)']
          config.build_settings['WARNING_CFLAGS'] << '-Wno-missing-template-arg-list-after-template-kw'
          
          # Disable all warnings flag
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'NO'
        end
      end
      
      # Remove -GCC_WARN_INHIBIT_ALL_WARNINGS from per-file flags
      if target.name == 'BoringSSL-GRPC'
        target.source_build_phase.files.each do |file|
          if file.settings && file.settings['COMPILER_FLAGS']
            flags = file.settings['COMPILER_FLAGS'].split
            flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
            file.settings['COMPILER_FLAGS'] = flags.join(' ')
          end
        end
      end
      
      # Patch gRPC-Core template syntax issue
      if target.name == 'gRPC-Core'
        grpc_file_path = 'Pods/gRPC-Core/src/core/lib/promise/detail/basic_seq.h'
        
        if File.exist?(grpc_file_path)
          file_content = File.read(grpc_file_path)
          problematic = 'Traits::template CallSeqFactory(f_, *cur_, std::move(arg))'
          fixed = 'Traits::template CallSeqFactory<>(f_, *cur_, std::move(arg))'
          
          if file_content.include?(problematic)
            puts "🔧 Patching gRPC-Core basic_seq.h for Xcode 16 compatibility"
            file_content.gsub!(problematic, fixed)
            File.open(grpc_file_path, 'w') { |f| f.write(file_content) }
          end
        end
      end
    end
    
    # React Native post install
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )
  end
end
